version: '3.7'
services:
  neo4j:
    image: neo4j:5-enterprise
    volumes:
      - ./data-bloom:/var/lib/neo4j/data
      - ./import:/var/lib/neo4j/import
      - ./licenses:/var/lib/neo4j/licenses
      - ./plugins:/var/lib/neo4j/plugins
    environment:
      NEO4J_AUTH: neo4j/please-change-this-password
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'
      NEO4J_dbms_bloom_license__file: /var/lib/neo4j/licenses/neo4j_bloom_licence.txt
      NEO4J_dbms_security_procedures_unrestricted: bloom.*,gds.*,apoc.*
      NEO4J_server_unmanaged__extension__classes: com.neo4j.bloom.server=/bloom
      NEO4J_dbms_security_http__auth__allowlist: /,/browser.*,/bloom.*
      NEO4J_server_memory_pagecache_size: 2G
      NEO4J_server_memory_heap_max__size: 8G
      NEO4J_ACCEPT_LICENSE_AGREEMENT: yes
    ports:
      - 7474:7474
      - 7687:7687
