version: '3.7'
services:
  neo4j:
    image: neo4j:5-community
    volumes:
      - ./data:/var/lib/neo4j/data
      - ./import:/var/lib/neo4j/import
    environment:
      NEO4J_AUTH: none
      NEO4J_PLUGINS: '["apoc"]'
    ports:
      - 7474:7474
      - 7687:7687